export enum StorageItem {
  USER = 'USER',
  TOKEN = 'TOKEN',
  REDIRECT_TO_AFTER = 'REDIRECT_TO_AFTER',
  BROWSER_TABS_COUNT = 'BROWSER_TABS_COUNT',
  BROWSER_STORAGE_TIME = 'BROWSER_STORAGE_TIME',
  BROWSER_CLOSED = 'BROWSER_CLOSED',
}
