import { Component } from '@angular/core';
import { AsianPokerSession } from '@features/entertainment/asian-poker/asian-poker-lobby.model';

@Component({
  selector: 'app-join-game',
  templateUrl: './join-game.component.html',
  styleUrls: ['./join-game.component.scss'],
})
export class JoinGameComponent {
  sessions: AsianPokerSession[] = [
    {
      id: 'WWWWWWWWWWWWWWW',
      title: 'WWWWWWWWWWWWWWW',
      hostId: 'xyz',
      hostDisplayName: 'Gracz 123',
      playersLimit: 5,
      playersJoined: 0,
      playersJoinedIds: [],
      accessibility: 'all',
      visibility: 'public',
      sessionState: 'lobby',
      actionDurationSeconds: 90,
      finishResult: null,
    },
    {
      id: 'abc',
      title: 'Super gra',
      hostId: 'xyz',
      hostDisplayName: 'Gracz 123',
      playersLimit: 5,
      playersJoined: 0,
      playersJoinedIds: [],
      accessibility: 'invite',
      visibility: 'public',
      sessionState: 'finished',
      actionDurationSeconds: 90,
      finishResult: null,
    },
    {
      id: 'abc',
      title: 'Super gra',
      hostId: 'xyz',
      hostDisplayName: 'Gracz 123',
      playersLimit: 5,
      playersJoined: 0,
      playersJoinedIds: [],
      accessibility: 'all',
      visibility: 'private',
      sessionState: 'lobby',
      actionDurationSeconds: 90,
      finishResult: null,
    },
    {
      id: 'WWWWWWWWWWWWWWW',
      title: 'WWWWWWWWWWWWWWW',
      hostId: 'xyz',
      hostDisplayName: 'Gracz 123',
      playersLimit: 5,
      playersJoined: 0,
      playersJoinedIds: [],
      accessibility: 'all',
      visibility: 'public',
      sessionState: 'lobby',
      actionDurationSeconds: 90,
      finishResult: null,
    },
    {
      id: 'abc',
      title: 'Super gra',
      hostId: 'xyz',
      hostDisplayName: 'Gracz 123',
      playersLimit: 5,
      playersJoined: 0,
      playersJoinedIds: [],
      accessibility: 'invite',
      visibility: 'public',
      sessionState: 'finished',
      actionDurationSeconds: 90,
      finishResult: null,
    },
    {
      id: 'abc',
      title: 'Super gra',
      hostId: 'xyz',
      hostDisplayName: 'Gracz 123',
      playersLimit: 5,
      playersJoined: 0,
      playersJoinedIds: [],
      accessibility: 'all',
      visibility: 'private',
      sessionState: 'lobby',
      actionDurationSeconds: 90,
      finishResult: null,
    },
    {
      id: 'WWWWWWWWWWWWWWW',
      title: 'WWWWWWWWWWWWWWW',
      hostId: 'xyz',
      hostDisplayName: 'Gracz 123',
      playersLimit: 5,
      playersJoined: 0,
      playersJoinedIds: [],
      accessibility: 'all',
      visibility: 'public',
      sessionState: 'playing',
      actionDurationSeconds: 90,
      finishResult: null,
    },
    {
      id: 'abc',
      title: 'Super gra',
      hostId: 'xyz',
      hostDisplayName: 'Gracz 123',
      playersLimit: 5,
      playersJoined: 0,
      playersJoinedIds: [],
      accessibility: 'invite',
      visibility: 'public',
      sessionState: 'finished',
      actionDurationSeconds: 90,
      finishResult: null,
    },
    {
      id: 'abc',
      title: 'Super gra',
      hostId: 'xyz',
      hostDisplayName: 'Gracz 123',
      playersLimit: 5,
      playersJoined: 0,
      playersJoinedIds: [],
      accessibility: 'all',
      visibility: 'private',
      sessionState: 'playing',
      actionDurationSeconds: 90,
      finishResult: null,
    },
    {
      id: 'WWWWWWWWWWWWWWW',
      title: 'WWWWWWWWWWWWWWW',
      hostId: 'xyz',
      hostDisplayName: 'Gracz 123',
      playersLimit: 5,
      playersJoined: 0,
      playersJoinedIds: [],
      accessibility: 'all',
      visibility: 'public',
      sessionState: 'lobby',
      actionDurationSeconds: 90,
      finishResult: null,
    },
    {
      id: 'abc',
      title: 'Super gra',
      hostId: 'xyz',
      hostDisplayName: 'Gracz 123',
      playersLimit: 5,
      playersJoined: 0,
      playersJoinedIds: [],
      accessibility: 'invite',
      visibility: 'public',
      sessionState: 'finished',
      actionDurationSeconds: 90,
      finishResult: null,
    },
  ];
}
